### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by OmarMWarraich**
### In this PR, following tasks have been completed:

- [ ] Development of the app around an external API.
- [ ] Use of an involvement API to record user interactions.
- [ ] Homepage, reservations and comments pop ups interfaces.
- [ ] Update likes and avoid double reentrancy for likes.
- [ ] Peer Code Review among partners..
- [ ] Video with project details.
       The Loom Video link is: https://www.loom.com/share/64926f2af33d4fabbf17f649235ce3bc

### CODE REVIEW

**Review by EricMbouwe — APPROVED** [review]
Hi @team, 

In my opinion, your project is ready for presentation! ⚡🔥 There is nothing else to say other than... it's time to merge it :shipit: 


Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Review by normainobary2021 — APPROVED** [review]
Hi team , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by normainobary2021 — APPROVED** [review]
Hi team , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by mohamed20163858 — APPROVED** [review]
fantastic great job everyone I think nothing we can add main functionalities is working perfectly.

**Pull request merged**
